workflows:
  m1-android-debug:
    name: M1 Android Debug
    max_build_duration: 120

    scripts:
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"

      - name: Show Java version
        script: |
          java -version

      - name: Show Gradle version
        script: |
          ./gradlew --version

      - name: Build M1 debug APK
        script: |
          ./gradlew assembleDebug --stacktrace

    artifacts:
      - app/build/outputs/**/*.apk