apply plugin: 'com.android.application'

android {
    namespace "com.neko68k.M1"
    compileSdk 35

    defaultConfig {
        applicationId "com.neko68k.M1"
        minSdk 26
        targetSdk 35
        ndk {
            abiFilters 'arm64-v8a'
        }

    }

    externalNativeBuild {
        ndkBuild {
            path file('src/main/jni/Android.mk')
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    dependencies {
        implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt'
        }
    }
}
